version: 2

sources:
  - name: fhir
    description: Raw FHIR resources loaded from NDJSON files into DuckDB
    schema: main
    tables:
      - name: diagnosticreport
      - name: immunization
      - name: observation
      - name: patient
